export const lang = {
  jp: {
    language: '日本語',//语言,
    noMore:'該当データなし',//没有更多了,
    noData:"該当データなし",
    close:"閉じる",//关闭
    change:"改訂",//修改
    reset:"リセット",//重置
    queding:"OK",//确定
    submit:"OK",//提交
    cancel:"キャンセル",//取消
    save:"OK",//  保存
    search:"検索",//搜索
    cancelDelete:"取消删除",//取消删除
    delete:"删除",
    operate:"操作",
    star:"開始日",//开始
    end:"終了日",//结束
    organizationName:"所属組織",//组织架构,
    staffName:"従業員氏名",//员工姓名
    alarmState:"アラームステータス",//告警状态
    reUpdate:"再アップロード",
    selectPic:"画像を選択",
    authorize:"授权",//授权
    level1:'レベル1',
    level2:'レベル2',
    level3:'レベル3',
    level4:'レベル4',
    level5:'レベル5',
    level6:'レベル6',
    level7:'レベル7',
    level8:'レベル8',
    level9:'レベル9',
    level10:'レベル10',
    has:"アラームあり",//有
    hasNot:"アラームなし",//无
    all:"すべて",//全部
    yes:"はい",//是
    NO:"いいえ",//否
    back:"戻る",
    up:"本人",//职员
    middle:"その他",//客户
    allUser:"本人 & その他",//所有人
    //
    uploadAvatar:"アバターがアップロードされていません",//未上传头像
    login:{
      loginTitle:"ユーザーログイン",
      placeholderUsername:"アカウント",
      placeholderPassword:"パスワード",
      messageEnterUsername:"ユーザー名を入力してください",
      messageEnterPassword:"パスワードを入力してください",
      btnLogin: 'ログイン',
      statusLoginSuccess:"ログイン成功",
      statusLogout:"サインアウト",
      confirmLogout:"確認する",
      confirmLogouttext:"終了を確認しますか?",
      cancelLogout:"キャンセル",
    },
    navList: {
      businessIndicators: "統計データ",//经营指标
      employeeView: "従業員一覧",//员工视图
      systemProgram: "システム設定",//系统设定
      AccountManagement: "アカウント管理",//账号管理
      OrganizationalSettings: "組織構造設定",//组织架构设定
      nursingHomeSettings: "施設設定",//养老院设定
      SensitiveWordSettings: "不適切ワード設定",//敏感词设定
      systemIntegration: "Webhook設定",//系统集成
      employeeManagement:"従業員管理",//员工管理
      changePassword: "確認する",//修改密码
      personalCenter:"マイページ",//个人中心
      signOut: "サインアウト",//退出登录
      EvaluationRanking:"検出数ランキング",//评价排名
      system:"システムについて",
    },
    employee:{
      employeeDayActive:"日間アクティブ指数",//员工日活跃度
      employeeWeekActive:"週間アクティブ指数",//员工周活跃度
      employeeMonthActive:"月間アクティブ指数",//员工月活跃度
      employeeQuarterlyActive:"四半期アクティブ指数",//员工季度活跃度
      employeeYearActive:"年アクティブ指数",//员工年活跃度
      employeeTotalNum:"デバイス登録数",//员工总人数
      employeeActiveNum:"デバイス稼働数",//员工激活总人数
      alarmStatTitle:"NGワード",//告警统计
      alarmStatToday:"日間",
      alarmStatWeek:"週間",
      alarmStatMonth:"月間",
      alarmStatQuarter:"今四半期",//季度
      alarmStatYear:"今年",//年
      alarmStatSync:"更新",// 更新
      alarmStatTotal:"アラーム総数",
      alarmStatMinor:"軽度",
      alarmStatMiddle:"中等度",
      alarmStatSerious:"重度",


    },
    staff:{
      alarmTitle:"アラーム",//告警
      normal:"正常",
      alarmStatTitle:"NGワード",//告警统计
      all:"アラーム履歴 計 ",//共
      waringNum:"件",//条告警
      level:"レベル",//等级
      chatRecord:"会話履歴",//聊天记录
      WebhookAddress:"Webhook アドレス",//Webhook地址
      WebhookSecretKey:"Webhook 秘密キー",//Webhook秘钥
      Copied:"クリップボードにコピーされました",//已复制到剪贴板
      keywordPlaceHolder:"キーワードを入力してください",//输入关键字
      viewContext:"コンテキストを表示する",//查看上下文
      good:"適切ワード",//好评
      bad:"不適切ワード",//差评
      t1:"アラーム履歴 不適切ワード 計",//告警历史 不良词 计
      t2:"アラーム履歴 適切ワード 計",//告警历史 夸奖词 计
      tooltip:{
        title:"アラート件数推移",
        good:"良い評価をいただきました",//收到好评
        bad:"否定的なレビューを受け取りました",//收到差评
        day1:'週間',
        day2:'月間',
        day3:'四半期',
        day4:'年間',
      }
    },
    staffMG:{
      keywordPlaceHolder:"従業員氏名",//输入员工姓名
      staffName:"従業員氏名",//头像/姓名
      staffAvatar:"アバター",////头像
      orgName:"所属組織",//所属组织
      jobNum:"従業員番号",//工号
      devSn:"デバイスSN",//员工设备SN
      editStaffInfo:"従業員情報を編集する",//编辑员工信息
      avatarKey:"従業員アバター",// 员工头像
      appName:"所属施設",// 所属养老院
      appId:"従業員が所属する老人ホーム申請ID",//员工所属养老院应用Id
      alarmStatus:"アラームステータス",//告警状态
      activeStatus:"アクティベーションステータス",//激活状态
      editorStaffInfo:"編集",//编辑
      operate:"操作する",//操作
      updateSuccess:"正常に変更されました",//修改成功
      updateFail:"編集に失敗する",//修改失败
      save:"保存",//保存
      reset:"リセット",//重置
      alarmStatus1:"アラームあり",//有告警
      alarmStatus2:"アラームなし",//无告警
      activeStatus1:"アクティブ化済",//已激活
      activeStatus2:"未アクティブ化",//未激活
      warningObj:{
        text1:"JPG / PNG形式ファイルのみアップロード可能",//上传头像图片只能是 JPG或者PNG 格式!
      }
    },
    sensitive:{
      SensitiveKeywords:"キーワード検索",//敏感关键词
      SensitiveKeywords2:"ワード詳細",//敏感关键词
      SensitivityLevel:"レベル",//敏感度等级
      SensitivityType:"タイプ",//敏感度类型
      sensitive:"タイプ",//敏感词检测类型
      sensitiveGood:"適切ワード",//夸奖词
      sensitiveBad:"不適切ワード",//负面词
      pleaseChoose:"タイプを選択",//请选择
      search:"検索",//搜索
      addSensitiveWords:"新規ワードの登録",//添加敏感词
      importSensitiveWords:"新規ワードの一括登録",//导入敏感词
      exportSensitiveWords:"ワードリストのダウンロード",//导出敏感词
      creationTime:"登録日",//创建时间
      button1:"Excelファイルをアップロード",
      button2:"xls/xlsxファイルのみアップロード可能",
      promptWordName:"検出ワードリスト名称",//敏感词检测场景
      associatedSensitiveWords:"検出ワード総数",//关联敏感词数量
      detectionSwitch:"OFF/ON",//检测开关
      todo:"編集",//操作
      delete:"消去",//删除
      checkKeyWord:"検出ワードを確認する",//查看敏感词
      keyword:"検出ワード",//敏感关键词
      level:"レベル",//敏感等级
      edit:"編集",//编辑
      sensitiveType:"タイプ",//敏感词检测类型
      v_keyword:"検出するワードを入力してください",//请输入敏感词
      v_level:"レベルを選択してください",//请选择敏感等级
      v_sensitiveType:"タイプを選択してください",//请选择敏感词类型
    },
    nursing:{
      nursingHomeName:"施設名称",//养老院名称
      nursingHomeOrganization:"所属組織",//所在组织
      operate:"編集",//操作
      associatedOrganizations:"組織連携",//关联组织
      updateSuccess:"組織連携が完了しました",//修改成功
      updateFail:"編集に失敗する",//修改失败
    },
    organization:{
      organization:"キーワード検索",//组织架构
      organization2:"組織名",//组织架构
      organizationName:"所属組織",//  组织名称
      organizationLevel:"組織階層",//组织架构层次
      createTime:"作成日",//创建时间
      operate:"編集",//操作
      edit:"編集",//编辑
      delete:"削除",//删除
      add:"既存組織の編集",
      deleteTips:"削除した組織は復元できません。続行しますか？",//删除提示
      deleteTipsTitle:"組織の削除",//提示
      queding:"OK",//确定
      cancel:"いいえ",//取消
      addOrg:"既存組織の編集",//新建组织架构
      parentOrg:"上位組織",//父级组织
      orgName:"組織名",//组织名称
      submit:"OK",//提交
      update:"更新する",//更新
      orgRevisedSuccess:"組織構造の再構築が完了しました",//校正组织机构层级和深度成功
      value_vo_orgName:"組織名を入力してください",//请输入组织名称
      value_vo_parentId:"上位組織を選択してください",//请选择父级组织
      root:"上位組織"
    },
    account:{
      search:"検索",//搜索
      createUser:"新規ユーザー作成",//创建用户
      AuthUser:"ユーザー認証",//用户授权
      createTime:"登録日",//创建时间
      updateTime:"変更日",//修改时间
      organizationName:"所属組織",//所在组织
      username:"ユーザー名",//用户名
      roleName:"役割",//角色名称
      role:"役割",//角色
      operate:"操作する",//操作
      edit:"編集",//编辑
      delete:"消去",//删除
      add:"新しい",//新建
      inputKeyWord:"キーワード検索",//输入关键字进行过滤
      parentORg:"所属組織",//所属组织
      password:"パスワード",//密码
      cancel:"キャンセル",//取消
      submit:"OK",//提交
      v_parentId:"所属組織を選択してください",//请选择一个组织
      v_username:"ユーザー名を入力してください",//请输入用户名
      v_username_e:"有効なメールアドレスを入力してください",//请输入有效的电子邮件地址
      v_password:"パスワードを入力してください",//请输入密码
      v_roleCode:"役割を選択してください",//请选择角色

    },
    Pension:{
      userId:"ユーザーID",//账号ID
      userName:"ユーザー名",//用户名
      organizationId:"所属組織ID",//机构id
      organizationName:"所属組織",//机构名称
      createTime:"登録日",//创建时间
      updateTime:"変更日",//更新时间
      update:"OK",//  修改
      save:"OK",//  保存
      cancel:"キャンセル",//取消
    },
    EvaluationRanking:{
      EvaluationRanking:"評価ランキング",//评价排行
      ranking:"順位",//排名
      avatarKey:"アバター",//头像
      staffName: "従業員氏名",//姓名
      jobNUm:"従業員番号",//工号
      orgName:"所属組織",//所属组织
      appName:"連携施設",//所属养老院
      alarmTotalNum:"ワード検出総数",//评价总数
      negativeNum:"不適切ワード検出数",//差评数量
      praiseNum:"適切ワード検出数",//好评数量
      tab_good:"適切ワード",//备受好评榜
      tab_bad:"不適切ワード"//备受差评榜
    },
    system:{
      title:"年金制度",//养老系统标题
      versionRecord:"バージョン履歴を表示する",//版本记录
      releaseRecord:"リリース記録",//发版记录
    },
    pushConfig:{
      title:"通知設定",//告警设置
      label_channel:"通知方式",//推送方式
      label_cycle:"通知頻度",//推送周期
      label_language:"通知言語",//推送模板
      label_levelList:"通知範囲",//告警级别
      value_email:"郵便",//邮件
      value_everyday:"毎日",//每日
      value_everyWeek:"毎週",//每周
      value_everyMon:"毎月",//每月
      zh:"中国語",//中文
      jp:"日本語",//日文
      level1:'レベル1',//一级告警
      level2:'レベル2',//二级告警
      level3:'レベル3',//三级告警
      level4:'レベル4',//四级告警
      level5:'レベル5',//五级告警
      level6:'レベル6',//六级告警
      level7:'レベル7',//七级告警
      level8:'レベル8',//八级告警
      level9:'レベル9',//九级告警
      level10:'レベル10',//十级告警
      formWaring:{
        text0:"通知するワードのレベルをすべて選択してください",//请选择
        text1:"请至少选择一个推送方式",//请至少选择一个推送方式
        text2:"请选择推送周期",//请选择推送周期
        text3:"请选择推送模板",//请选择推送模板
        text4:"通知するワードのレベルをすべて選択してください",//请选择告警级别
      }
    },
  },
  zh: {
    language:'中文',//语言,
    noMore:'没有更多了',//没有更多了,
    noData:"没有数据",
    close:"关闭",
    change:"修改",
    reset:"重置",//重置
    submit:"提交",
    queding:"确定",
    operate:"操作",
    cancel:"取消",//取消
    save:"保存",//  保存
    search:"搜索",
    organizationName:"组织架构",
    staffName:"员工姓名",
    alarmState:"告警状态",//告警状态
    back:"返回",
    all:"全部",
    delete:"删除",
    authorize:"授权",//授权
    yes:"是",
    cancelDelete:"取消删除",
    NO:"否",
    star:"开始",
    end:"结束",
    has:"有",
    hasNot:"无",
    uploadAvatar:"未上传头像",
    reUpdate:"重新上传",
    selectPic:"选择图片",
    account:{
      search:"搜索",
      createUser:"创建用户",
      AuthUser:"用户授权",
      createTime:"创建时间",
      updateTime:"修改时间",
      organizationName:"所属组织",
      username:"用户名",
      roleName:"角色名称",
      role:"角色",//角色
      operate:"操作",
      edit:"编辑",
      delete:"删除",
      add:"新建",
      parentORg:"所属组织",
      inputKeyWord:"输入关键字进行过滤",
      password:"密码",//密码
      cancel:"取消",
      submit:"提交",
      v_parentId:"请选择一个组织",
      v_username:"请输入用户名",
      v_username_e:"请输入有效的电子邮件地址",
      v_password:"请输入密码",
      v_roleCode:"请选择角色",

    },
    up:"职员",//职员
    level1:'等级1',
    level2:'等级2',
    level3:'等级3',
    level4:'等级4',
    level5:'等级5',
    level6:'等级6',
    level7:'等级7',
    level8:'等级8',
    level9:'等级9',
    level10:'等级10',
    middle:"客户",//客户
    allUser:"所有人",//所有人
    login:{
      loginTitle:"用户登录",
      placeholderUsername:"账号",
      placeholderPassword:"密码",
      messageEnterUsername:"请输入账号",
      messageEnterPassword:"请输入密码",
      btnLogin:'登录',
      statusLoginSuccess:"登录成功",
      statusLogout:"退出登录",
      confirmLogout:"确认",
      confirmLogouttext:"确认退出吗？",
      cancelLogout:"取消",

    },
    navList:{
      businessIndicators:"经营指标",
      employeeView:"员工视图",
      systemProgram:"系统设定",
      AccountManagement:"账号管理",
      OrganizationalSettings:"组织架构设定",
      nursingHomeSettings:"养老院设定",
      SensitiveWordSettings:"敏感词设定",
      systemIntegration:"系统集成",
      employeeManagement:"员工管理",
      personalCenter:"个人中心",
      changePassword:"修改密码",
      signOut:"退出登录",
      EvaluationRanking:"评价排行",
      system:"关于系统",
    },
    employee:{
      employeeDayActive:"员工日活跃度",
      employeeWeekActive:"员工周活跃度",
      employeeMonthActive:"员工月活跃度",
      employeeQuarterlyActive:"员工季度活跃度",
      employeeYearActive:"员工年活跃度",
      employeeTotalNum:"员工总人数",
      employeeActiveNum:"员工激活总人数",
      alarmStatTitle:"告警统计",
      alarmStatToday:"今日",
      alarmStatWeek:"本周",
      alarmStatMonth:"本月",
      alarmStatQuarter:"本季度",
      alarmStatYear:"本年度",
      alarmStatSync:"更新",
      alarmStatTotal:"总告警数",
      alarmStatMinor:"轻微",
      alarmStatMiddle:"中危",
      alarmStatSerious:"严重",


    },
    staff:{
      alarmTitle:"告警",
      normal:"正常",
      alarmStatTitle:"告警统计",
      all:"共",
      t1:"共",
      t2:"共",
      waringNum:"条告警",
      level:"等级",
      chatRecord:"聊天记录",
      WebhookAddress:"Webhook地址",
      keywordPlaceHolder:"请输入关键字",
      WebhookSecretKey:"Webhook秘钥",
      Copied:"已复制到剪贴板",
      viewContext:"查看上下文",
      good:"好评",
      bad:"差评",
      tooltip:{
        title:"评价趋势图",
        good:"收到好评",
        bad:"收到差评",
        day1:'最近7天',
        day2:'最近1月',
        day3:'最近1季度',
        day4:'最近1年',
      }

    },
    sensitive:{
      SensitiveKeywords:"敏感关键词",
      SensitiveKeywords2:"敏感关键词",
      SensitivityLevel:"敏感等级",
      SensitivityType:"敏感词类型",
      sensitive:"敏感词检测类型",//敏感词检测类型
      sensitiveGood:"夸奖词",//夸奖词
      sensitiveBad:"负面词",//负面词
      pleaseChoose:"请选择",
      search:"搜索",
      addSensitiveWords:"添加敏感词",
      importSensitiveWords:"导入敏感词",
      keyword:"敏感关键词",
      level:"敏感等级",
      sensitiveType:"敏感词检测类型",
      exportSensitiveWords:"导出敏感词",
      creationTime:"创建时间",
      button1:"点击上传Excel文件",
      button2:"只能上传xls/xlsx格式的文件",
      promptWordName:"敏感词检测场景",
      associatedSensitiveWords:"敏感词设定数量",
      detectionSwitch:"检测开关",
      todo:"操作",
      delete:"删除",
      edit:"编辑",
      checkKeyWord:"查看敏感词",
        v_keyword:"请输入敏感词",
        v_level:"请选择敏感等级",
        v_sensitiveType:"请选择敏感词类型",


    },
    nursing:{
      nursingHomeName:"养老院名称",
      nursingHomeOrganization:"所在组织",
      operate:"操作",
      associatedOrganizations:"关联组织",
      updateSuccess:"修改成功",//修改成功
      updateFail:"修改失败",//修改失败
    },
    staffMG:{
      editStaffInfo:"编辑员工信息",
      keywordPlaceHolder:"员工姓名",
      staffName:"头像/姓名",
      staffAvatar:"员工头像",//
      orgName:"所属组织",
      jobNum:"工号",
      devSn:"设备SN",
      avatarKey:"员工头像",
      appName:"所属养老院",
      appId:"员工所属养老院应用Id",
      alarmStatus:"告警状态",
      alarmStatus1:"有告警",
      alarmStatus2:"无告警",
      activeStatus:"激活状态",
      activeStatus1:"已激活",//已激活
      activeStatus2:"未激活",//未激活
      editorStaffInfo:"编辑",
      operate:"操作",
      updateSuccess:"修改成功",//修改成功
      updateFail:"修改失败",//修改失败
      save:"保存",//保存
      reset:"重置",//重置
      warningObj:{
        text1:"上传头像图片只能是 JPG或者PNG 格式!",
      }
    },
    organization:{
      organization:"组织架构",
      organization2:"组织架构",
      organizationName:"组织名称",
      organizationLevel:"组织架构层次",
      createTime:"创建时间",
      operate:"操作",
      edit:"编辑",
      delete:"删除",
      authorize:"授权",
      add:"新建",
      deleteTips:"此操作将永久删除该组织架构, 是否继续?",
      deleteTipsTitle:"提示",
      queding:"确定",
      cancel:"取消",
      addOrg:"新建组织架构",
      parentOrg:"父级组织",
      orgName:"组织名称",
      submit:"提交",//提交
      update:"更新",//更新
      orgRevisedSuccess:"校正组织机构层级和深度成功",//校正组织机构层级和深度成功
      value_vo_orgName:"请输入组织名称",
      value_vo_parentId:"请选择父级组织",
      root:"根组织"

    },
    Pension:{
      userId:"账号ID",
      userName:"用户名",
      organizationId:"机构id",
      organizationName:"所属组织",
      createTime:"创建时间",
      updateTime:"更新时间",
      update:"修改",
      save:"保存",
      cancel:"取消",
    },
    EvaluationRanking:{
      ranking:"排行",
      avatarKey:"头像",
      staffName:"姓名",
      jobNUm:"工号",
      orgName:"所属区域组织",
      appName:"所属养老院",
      alarmTotalNum:"评价总数",
      negativeNum:"差评数量",
      praiseNum:"好评数量",
      tab_good:"备受好评榜",
      tab_bad:"备受差评榜"


    },
    system:{
      title:"养老系统",
      versionRecord:"查看版本记录",
      releaseRecord:"发版记录",
    },
    pushConfig:{
      title:"配置告警推送",//告警设置
      label_channel:"推送方式",
      label_cycle:"推送周期",
      label_language:"推送模板",
      label_levelList:"告警级别",
      value_email:"邮件",
      value_everyday:"每日",
      value_everyWeek:"每周",
      value_everyMon:"每月",
      zh:"中文",
      jp:"日文",
      level1:'等级1',
      level2:'等级2',
      level3:'等级3',
      level4:'等级4',
      level5:'等级5',
      level6:'等级6',
      level7:'等级7',
      level8:'等级8',
      level9:'等级9',
      level10:'等级10',
      formWaring:{
        text0:"请选择",
        text1:"请至少选择一个推送方式",
        text2:"请选择推送周期",
        text3:"请选择推送模板",
        text4:"请选择告警级别",
      }
    },
  }
}
